#!/usr/bin/env ruby
require 'yaml'

def load_config!
  @config = YAML.load(File.read("#{ENV['HOME']}/.config/watch_tablet.yml"))
end

def config
  load_config! unless @config
  @config
end

def activate_mode(mode)
  puts "Switching to #{mode} mode"
  if cmds = config['modes'][mode]
    cmds.each{|cmd| system cmd }
  end
end

def run_watcher
  cmd = "monitor-sensor"
  io = IO.popen(cmd,"r")
  while s=io.gets
    if m=s.match(/Accelerometer orientation changed: (.*?)$/)
      activate_mode(m[1])
    end
  end
rescue Interrupt
  io.close
end

run_watcher
